function p = pdfCopulaGalambos(u1,u2,theta)
    u1tilde = -log(u1);
    u2tilde = -log(u2);
    cdf = u1 .* u2 .* exp( (u1tilde.^(-theta) + u2tilde.^(-theta)).^(-1./theta) );
    p = 1 - ...
        (u1tilde.^(-theta) + u2tilde.^(-theta)).^(-1./theta - 1) .* ...
        (u1tilde.^(-theta - 1) + u2tilde.^(-theta - 1)) + ...
        (u1tilde.^(-theta) + u2tilde.^(-theta)).^(-1./theta - 2) .* ...
        (u1tilde .* u2tilde).^(-1-theta) .* ...
        (1 + theta + (u1tilde.^(-theta) + u2tilde.^(-theta)).^(-1./theta));
    p = cdf ./ (u1 .* u2) .* p;
end
